### ISSUE TITLE
Allow customising the job description

### ISSUE THREAD

**Issue by zerolab** [mozilla/wagtail-localize-smartling#25]
a. via the translation component
b. via something like a `WAGTAIL_LOCALIZE_DESCRIPTION_CALLBACK_FUNC` that would automatically append to the job description whatever the callback returns

**Comment by zerolab** [comment]
@stevejalim should the callback be additive, replacing or.. leave it to the implementer?

**Comment by stevejalim** [comment]
Hi @zerolab - apols for the delay

I think making it "implementers choice" is good. The callback function can then add, delete or replace content as it sees fit and just has to commit to returning the same type as it was passed.

How's that seem to you?

**Comment by zerolab** [comment]
Sounds like a plan

**Comment by zerolab** [comment]
@stevejalim current the default description https://github.com/mozilla/wagtail-localize-smartling/blob/5d3a79a100dac9764f38cd22ec4b060f3c4176eb/src/wagtail_localize_smartling/models.py#L267-L289 takes the translation source and target translation as params. 
Are you happy with just those, or would having things like the user and due date (optional) be helpful? this is one of the things I went in circles with 🤦🏼 

Note, we pass the description in https://github.com/mozilla/wagtail-localize-smartling/blob/5d3a79a100dac9764f38cd22ec4b060f3c4176eb/src/wagtail_localize_smartling/models.py#L292 which gets called when one chooses to send the translation to Smartling

**Comment by stevejalim** [comment]
@zerolab Thanks for this!

I think the user and due date aren't particularly useful for a description - the user is likely not relevant to the translator (and sends PII to a third party, which I try to avoid here), and the due date is elsewhere in the system.

I think in reality, the Bedrock-specific use case needs the following (_but_ I am not asking for these as extra core behaviour, just making them possible via a callback option that I can configure myself would be perfect.)

1. To generate and inject a sharing URL (from https://github.com/mozmeao/wagtaildraftsharing) so that a translator could get a link to view the en-US version of the Page that doesn't need auth even if it's currently not published.
2. Show the title of the relevant page in the Job.

This assumes that one source-lang Page maps cleanly to one Job, which it seems to based on tests in Smartling, but please correct me if I'm wrong there.

If I am not wrong, I wonder if it'd be easy (ahem) to allow the callback function to patch the `edit_url` param and the `description` string, and to be passed args/kwargs that let us get hold of the revision involved in the Job (which lets us get the Page).
